export const screens =  {
   SPLASHSCREEN : "Splash",
   WELCOMESCREEN: "Welcome",
   WELCOMESCREEN2: "Welcome2",
   WELCOMESCREEN3: "Welcome3",
   LOGIN: "Login",
   SIGNUP: "Signup",
   VERIFICATION: "Verification",
   REGISTRATIONSUCCESS: "RegistrationSuccess",
   HOME: "Home",
   SUBCATEGORIES: "SubCategories",
   PRODUCTDETAIL: "ProductDetail",
   EXPLORE: "Explore",
   PROFILESETTING: "ProfileSetting",
   SAVEDADDRESS: "SavedAddress",
   ADDNEWADDRESS: "AddNewAddress",
   SELLERINFO: "SellerInfo",
   MYPRODUCTS: "MyProducts",
   MYORDERS: "MyOrders",
   BECOMEASELLER: "BecomeASeller",
   EARNINGS: "Earnings",
   ORDER_DETAILS: "OrderDetails",
   ADD_REVIEW: "AddReview",
   SEARCH_PRODUCTS: "SearchProducts",
   PRODUCT_LISTING: "ProductListing",
   ADD_NEW_PRODUCT: "AddNewProduct",
   NOTIFICATION_LIST: "NotificationList",
   CONTACT_US: "ContactUs",
   PRIVACY_POLICY: "PrivacyPolicy",
   TERMSANDCONDITIONS: "TermsAndConditions",
   MY_CART: "MyCart",
   CHAT: "Chat",
   PAYMENT: "Payment",
   ORDER_SUCCESS: "OrderSuccess",
   PAYMENT_DETAILS: "PaymentDetails",
   WISHLIST: "WishList",
   CHANGEPASSWORD: "ChangePassword",
   FORGOTPASSWORD: "ForgotPassword",
   RESETPASSWORD: "ResetPassword",
   BUSINESSDETAILS: "BusinessDetails",
   SELLERDELIVERYGUIDE: "SellerDeliveryGuide"
}
export default screens;